spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxi-finder
    username: root
    password: Secret123#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-request-size: 10000MB
      max-file-size: 10000MB

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
